---
jobs:
  docker-lint:
    docker:
      - image: vpgrp/linter:docker-lint
    steps:
      - checkout
      - run:
          name: docker linting
          command: /usr/bin/docker-lint Dockerfile
  mdl-lint:
    docker:
      - image: vpgrp/linter:markdown-lint
    steps:
      - checkout
      - run:
          name: markdown linting
          command: /usr/bin/markdown-lint .
  markdown-lint:
    docker:
      - image: sdesbure/remark-lint:latest
    steps:
      - checkout
      - run:
          name: change path to markdown lint
          command: "cd /usr/src/app"
      - run:
          name: markdown linting
          command: "node_modules/.bin/remark --frail --use remark-preset-lint-recommended --use remark-preset-lint-consistent ${CIRCLE_WORKING_DIRECTORY}"
workflows:
  version: 2
  lint:
    jobs:
      - docker-lint
      - mdl-lint
      - markdown-lint
